# Generated by Django 4.1.7 on 2023-05-11 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Egresso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SugestoesRelacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestoes_relacao', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='SugestoesHomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sugestoes_homepage', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='InsercaoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teve_experiencia_trabalho', models.BooleanField()),
                ('area_formacao', models.CharField(max_length=50)),
                ('situacao_atual', models.CharField(max_length=50)),
                ('como_conseguiu_trabalho', models.CharField(max_length=100)),
                ('tipo_vinculo', models.CharField(max_length=100)),
                ('trabalho_na_area', models.CharField(max_length=50)),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciasIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencias', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='ExperienciaFormativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_escolha', models.TextField()),
                ('expectativas_curso', models.CharField(max_length=50)),
                ('aprendizado', models.CharField(max_length=50)),
                ('avaliacao_curso', models.CharField(max_length=50)),
                ('participacao_pesquisa', models.BooleanField()),
                ('participacao_extensao', models.BooleanField()),
                ('foi_monitor', models.BooleanField()),
                ('realizou_estagio', models.BooleanField()),
                ('experiencia_monitor_estagio', models.TextField()),
                ('dificuldades_curso', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='Estudando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso_superior', models.BooleanField()),
                ('nome_curso', models.CharField(max_length=100)),
                ('nome_instituicao', models.CharField(max_length=100)),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='EgressoCaracterizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_conclusao', models.IntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('renda_bruta_mensal', models.CharField(max_length=50)),
                ('nivel_escolaridade', models.CharField(max_length=50)),
                ('curso_superior', models.CharField(max_length=100)),
                ('instituicao_superior', models.CharField(max_length=100)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.curso')),
                ('egresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='DificuldadesTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldades', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
        migrations.CreateModel(
            name='Contribuicoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribuicoes', models.TextField()),
                ('egresso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pesquisa_egresso.egresso')),
            ],
        ),
    ]
