# Generated by Django 4.1.7 on 2023-05-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('curso', models.CharField(max_length=100)),
                ('ano_conclusao', models.PositiveIntegerField()),
                ('sexo', models.CharField(max_length=10)),
                ('idade', models.PositiveIntegerField()),
                ('estado_civil', models.CharField(max_length=20)),
                ('renda_bruta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('nivel_escolaridade', models.CharField(max_length=50)),
                ('curso_superior', models.CharField(max_length=100)),
                ('motivo_escolha_curso', models.TextField()),
                ('expectativas_curso', models.TextField()),
                ('avaliacao_aprendizado', models.PositiveIntegerField()),
                ('avaliacao_curso', models.PositiveIntegerField()),
                ('participacao_pesquisa', models.BooleanField()),
                ('participacao_extensao', models.BooleanField()),
                ('monitor', models.BooleanField()),
                ('realizacao_estagios', models.BooleanField()),
                ('contribuicao_monitor_estagio', models.TextField()),
                ('experiencia_trabalho', models.TextField()),
                ('trabalho_area_formacao', models.CharField(max_length=100)),
                ('situacao_atual', models.CharField(max_length=50)),
                ('meio_conseguir_trabalho', models.TextField()),
                ('tipo_vinculo', models.CharField(max_length=50)),
                ('instituicao', models.CharField(max_length=100)),
                ('nome_curso', models.CharField(max_length=100)),
                ('contribuicoes_if', models.TextField()),
                ('dificuldades_curso', models.TextField()),
                ('experiencias_if', models.TextField()),
                ('sugestoes_relacao', models.TextField()),
                ('sugestoes_homepage', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='dificuldadestrabalho',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='egressocaracterizacao',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='egressocaracterizacao',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='estudando',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='experienciaformativa',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='experienciasif',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='insercaotrabalho',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='sugestoeshomepage',
            name='egresso',
        ),
        migrations.RemoveField(
            model_name='sugestoesrelacao',
            name='egresso',
        ),
        migrations.DeleteModel(
            name='Contribuicoes',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='DificuldadesTrabalho',
        ),
        migrations.DeleteModel(
            name='Egresso',
        ),
        migrations.DeleteModel(
            name='EgressoCaracterizacao',
        ),
        migrations.DeleteModel(
            name='Estudando',
        ),
        migrations.DeleteModel(
            name='ExperienciaFormativa',
        ),
        migrations.DeleteModel(
            name='ExperienciasIF',
        ),
        migrations.DeleteModel(
            name='InsercaoTrabalho',
        ),
        migrations.DeleteModel(
            name='SugestoesHomePage',
        ),
        migrations.DeleteModel(
            name='SugestoesRelacao',
        ),
    ]
