# Generated by Django 4.1.7 on 2023-05-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0003_alter_pesquisa_ano_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1),
        ),
    ]
