# Generated by Django 4.1.7 on 2023-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0004_alter_pesquisa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='estado_civil',
            field=models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('divorciado', 'Divorciado'), ('viuvo', 'Viúvo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='nivel_escolaridade',
            field=models.CharField(choices=[('fundamental', 'Ensino Fundamental'), ('medio', 'Ensino Médio'), ('tecnico', 'Ensino Técnico'), ('superior', 'Ensino Superior'), ('pos_graduacao', 'Pós-Graduação'), ('mestrado', 'Mestrado'), ('doutorado', 'Doutorado')], max_length=50),
        ),
    ]
