# Generated by Django 4.1.7 on 2023-05-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0005_alter_pesquisa_estado_civil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_aprendizado',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('media', 'Média'), ('bom', 'Bom'), ('otimo', 'Ótimo')], max_length=10, verbose_name='Avaliação Aprendizado'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_curso',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('media', 'Média'), ('bom', 'Bom'), ('otimo', 'Ótimo')], max_length=10, verbose_name='Avaliação do Curso'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='contribuicoes_if',
            field=models.TextField(verbose_name='Contribuições do IF'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='situacao_atual',
            field=models.CharField(max_length=50, verbose_name='Situação Atual'),
        ),
    ]
