# Generated by Django 4.1.7 on 2023-05-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0006_alter_pesquisa_avaliacao_aprendizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_aprendizado',
            field=models.CharField(max_length=10, verbose_name='Avaliação Aprendizado'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_curso',
            field=models.CharField(max_length=10, verbose_name='Avaliação do Curso'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
