# Generated by Django 4.1.7 on 2023-05-16 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0007_alter_pesquisa_avaliacao_aprendizado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='curso_superior',
        ),
        migrations.RemoveField(
            model_name='pesquisa',
            name='nome_curso',
        ),
    ]
