# Generated by Django 4.1.7 on 2023-05-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0008_remove_pesquisa_curso_superior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_aprendizado',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('media', 'Média'), ('bom', 'Bom'), ('otimo', 'Ótimo')], max_length=10, verbose_name='Avaliação Aprendizado'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='avaliacao_curso',
            field=models.CharField(choices=[('ruim', 'Ruim'), ('media', 'Média'), ('bom', 'Bom'), ('otimo', 'Ótimo')], max_length=10, verbose_name='Avaliação do Curso'),
        ),
    ]
