# Generated by Django 4.1.7 on 2023-05-17 01:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0009_alter_pesquisa_avaliacao_aprendizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa',
            name='contribuicao_monitor_estagio',
            field=ckeditor.fields.RichTextField(verbose_name='Contribuição monitor estagio'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='contribuicoes_if',
            field=ckeditor.fields.RichTextField(verbose_name='Contribuições do IF'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='dificuldades_curso',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='expectativas_curso',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='experiencia_trabalho',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='experiencias_if',
            field=ckeditor.fields.RichTextField(verbose_name='Experiencias IF'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='meio_conseguir_trabalho',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='motivo_escolha_curso',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='sugestoes_homepage',
            field=ckeditor.fields.RichTextField(verbose_name='Sugestões homepage'),
        ),
        migrations.AlterField(
            model_name='pesquisa',
            name='sugestoes_relacao',
            field=ckeditor.fields.RichTextField(verbose_name='Sugestões relação'),
        ),
    ]
