# Generated by Django 4.1.7 on 2023-05-17 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0011_titula_form'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titula_Form',
            new_name='Titulo_Form',
        ),
    ]
