# Generated by Django 4.1.7 on 2023-05-17 02:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0012_rename_titula_form_titulo_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo_form',
            name='titulo',
            field=ckeditor.fields.RichTextField(verbose_name='titulo'),
        ),
    ]
