# Generated by Django 4.1.7 on 2023-05-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_remove_politica_arquivo_politica_politica_and_more'),
        ('pesquisa_egresso', '0013_alter_titulo_form_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesquisa',
            name='campi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.campi', verbose_name='Campus'),
        ),
    ]
