# Generated by Django 4.1.7 on 2023-05-17 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesquisa_egresso', '0014_pesquisa_campi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesquisa',
            name='campi',
        ),
    ]
