# Generated by Django 4.1.7 on 2023-03-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_curso', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Depoimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img_perfil')),
                ('turma', models.CharField(max_length=20)),
                ('depoimento', models.TextField()),
                ('autorizacao_publicacao', models.BooleanField(default=False)),
                ('aceite_politica_privacidade', models.BooleanField(default=False)),
                ('aprovado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.curso')),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Home.nivel_curso')),
            ],
        ),
    ]
