# Generated by Django 4.1.7 on 2023-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_apresentacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='texto_esquerdo',
            field=models.TextField(max_length=40, verbose_name='Texto esquerda'),
        ),
    ]
