# Generated by Django 4.1.7 on 2023-04-26 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_pesquisa_egresso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesquisa_egresso',
            name='subtitulo',
            field=models.CharField(max_length=30, verbose_name='Subtitulo'),
        ),
        migrations.AlterField(
            model_name='pesquisa_egresso',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
