# Generated by Django 4.1.7 on 2023-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_pesquisa_egresso_subtitulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rodape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('links_importantes', models.CharField(max_length=200, verbose_name='Links importantes')),
                ('servicos', models.CharField(max_length=150, verbose_name='Serviços')),
                ('endereço', models.TextField(verbose_name='Endereço')),
            ],
        ),
    ]
