# Generated by Django 4.1.7 on 2023-04-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_rodape'),
    ]

    operations = [
        migrations.AddField(
            model_name='rodape',
            name='link_serviço',
            field=models.CharField(max_length=200, null=True, verbose_name='URL serviço'),
        ),
        migrations.AddField(
            model_name='rodape',
            name='nome_link',
            field=models.CharField(max_length=30, null=True, verbose_name='Nome do Link'),
        ),
        migrations.AlterField(
            model_name='rodape',
            name='links_importantes',
            field=models.CharField(max_length=200, verbose_name='URL'),
        ),
    ]
