# Generated by Django 4.1.7 on 2023-04-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_rodape_link_serviço_rodape_nome_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rodape',
            old_name='link_serviço',
            new_name='link_servico',
        ),
    ]
