# Generated by Django 4.1.7 on 2023-04-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_endereco_rodape_kinks_rodape_servico_delete_rodape'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rodape_kinks',
            new_name='Rodape_links',
        ),
    ]
