# Generated by Django 4.1.7 on 2023-04-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_rename_rodape_kinks_rodape_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endereco',
            old_name='endereço',
            new_name='endereco',
        ),
    ]
