# Generated by Django 4.1.7 on 2023-04-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_slaider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epregos_cerreira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo pagina Empregos e carreiras')),
                ('texto', models.TextField(verbose_name='Texto da descrição ')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40, verbose_name='Titulo pagina de Objetivo')),
                ('texto', models.TextField(verbose_name='Texto da descrição do objetivo')),
            ],
        ),
    ]
