# Generated by Django 4.1.7 on 2023-04-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_epregos_cerreira_objetivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campus', models.CharField(max_length=50, verbose_name='Campus')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='campus',
            field=models.ManyToManyField(related_name='cursos', to='Home.campus'),
        ),
    ]
