# Generated by Django 4.1.7 on 2023-04-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_campus_curso_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descricao',
            field=models.TextField(null=True),
        ),
    ]
