# Generated by Django 4.1.7 on 2023-04-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_curso_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campus',
            new_name='Campi',
        ),
    ]
