# Generated by Django 4.1.7 on 2023-04-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_curso_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='depoimento',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Home.campi'),
        ),
    ]
