# Generated by Django 4.1.7 on 2023-04-28 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_depoimento_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depoimento',
            name='nivel',
        ),
    ]
