# Generated by Django 4.1.7 on 2023-05-02 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contato',
            name='enviado_boas_vindas',
            field=models.BooleanField(default=False, verbose_name='Email de confirmação'),
        ),
    ]
