# Generated by Django 4.1.7 on 2023-05-17 01:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0026_alter_apresentacao_texto_direita_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='depoimento',
            name='depoimento',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='endereco',
            field=ckeditor.fields.RichTextField(verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='epregos_cerreira',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto da descrição '),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='corpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='objetivos',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='Texto da descrição do objetivo'),
        ),
        migrations.AlterField(
            model_name='pesquisa_egresso',
            name='texto',
            field=ckeditor.fields.RichTextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='pesquisa_egresso',
            name='texto_direita',
            field=ckeditor.fields.RichTextField(verbose_name='texto direita'),
        ),
    ]
