# Generated by Django 4.1.7 on 2023-05-17 02:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_alter_curso_descricao_alter_depoimento_depoimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apresentacao',
            name='texto_esquerdo',
            field=ckeditor.fields.RichTextField(max_length=400, verbose_name='Texto esquerda'),
        ),
    ]
