# Generated by Django 4.1.7 on 2023-05-17 14:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0028_alter_apresentacao_texto_esquerdo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politica',
            name='arquivo',
        ),
        migrations.AddField(
            model_name='politica',
            name='politica',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Politica de Privacidade'),
        ),
        migrations.AlterField(
            model_name='apresentacao',
            name='texto_esquerdo',
            field=ckeditor.fields.RichTextField(verbose_name='Texto esquerda'),
        ),
    ]
