# Generated by Django 4.1.7 on 2023-05-30 19:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_remove_politica_arquivo_politica_politica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaider',
            name='btn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Botão'),
        ),
        migrations.AddField(
            model_name='slaider',
            name='texto_banner',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Paragrafo Banner'),
        ),
        migrations.AddField(
            model_name='slaider',
            name='titulo_banner',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Titulo Banner'),
        ),
        migrations.AddField(
            model_name='slaider',
            name='url_btn',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Link do Banner'),
        ),
    ]
